name: ci

on: [push]

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Java
        id: setup-jre
        uses: actions/setup-java@v1
        with:
          java-version: "11"
          architecture: x64

      - name: Compile
        run: ./gradlew compileJava